# SPDX-FileCopyrightText: Â© 2026 Romain Brault <mail@romainbrault.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[version]
source = "vcs"

[metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"

[[metadata.hooks.fancy-pypi-readme.fragments]]
path = "README.md"

[build.targets.sdist]
only-include = [
    "src/test_gh_rtd_mit_or_apache_2_0_macos_39",
]

[build.targets.wheel]
packages = [
    "src/test_gh_rtd_mit_or_apache_2_0_macos_39",
]
only-packages = true
artifacts = [
    "**/*.mo",
]
exclude = [
    "**/*.po",
    "**/*.pot",
]

[build.hooks.custom]
dependencies = [
    "babel>=1.25.0",
    "setuptools>=2.16.0",
    "typing-extensions>=4.12.1; python_version<'3.12'",
]
