# SPDX-FileCopyrightText: Â© 2026 Romain Brault <mail@romainbrault.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

version = 1
SPDX-PackageName = "test_gh_rtd_mit_or_apache_2_0_macos_39"
SPDX-PackageSupplier = "whiteprints-tests <mail@romainbrault.com>"
